version: '3.7'

services:
  client:
    image: "salimfadhley/freedom-bot:latest"
    build:
      context: .
      target: py
    volumes:
    - ./src:/src:ro
    - ~/.config/simpleclient:/config/simpleclient:ro
    entrypoint: /usr/local/bin/run_client
    env_file:
      - .environment
#    links:
#      - localstack
    networks:
      - internal

  python:
    image: "salimfadhley/freedom-bot:latest"
    build:
      context: .
      target: py
    volumes:
      - ./src:/src:ro
      - ~/.config/simpleclient:/config/simpleclient:ro
    env_file:
      - .environment
    networks:
      - internal

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
      - TMPDIR=/tmp/localstack
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - internal

networks:
  internal:

