version: '3.7'

services:
  client:
    image: "salimfadhley/freedom-bot:latest"
    build:
      context: .
      target: py
    volumes:
    - ./src:/src:ro
    - ~/.config/simpleclient:/root/.config/simpleclient:ro
    - "/tmp/.tdlib_files/:/tmp/.tdlib_files/"
    - "./storage:/storage"
    - "session:/session"
    entrypoint: run_client
    env_file:
      - .environment
    environment:
      SESSION_LOCATION: "/session"
      STORAGE_LOCATION: "/storage"
    links:
      - elastic
      - kibana
    networks:
      - internal

  python:
    image: "salimfadhley/freedom-bot:latest"
    build:
      context: .
      target: py
    volumes:
      - ./src:/src:ro
      - ~/.config/simpleclient:/root/.config/simpleclient:ro
      - "/tmp/.tdlib_files/:/tmp/.tdlib_files/"
      - "./storage:/storage"
      - "session:/session"
    env_file:
      - .environment
    environment:
      SESSION_LOCATION: "/session"
    networks:
      - internal
    ports:
    - "8888:8888"
    links:
      - elastic
      - kibana

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elastic
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - internal

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elastic:9200
      ELASTICSEARCH_HOSTS: http://elastic:9200
    networks:
      - internal
    ports:
    - "5601:5601"
    links:
      - elastic

networks:
  internal:

volumes:
  session:
  elastic_data:
  kibana:
