# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install tools
      run: |
        python -m pip install --upgrade pip setuptools wheel twine black mypy
    - name: Install dependencies
      run: |
        python -m pip install .
    - name: Style check
      run: |
          python -m black --check ./src/
    - name: Type check
      run: |
          python -m mypy
